TASK [Run Flask DB migrations and create DB] ****************************************************************************************************************************************************
fatal: [app-flask]: FAILED! => {"changed": true, "cmd": ". \"/var/www/article_pool/venv/bin/activate\"\nexport FLASK_APP=app.py\nflask db upgrade\npython3 -m app.create_db\n", "delta": "0:02:01.336039", "end": "2025-06-06 18:00:35.419000", "msg": "non-zero return code", "rc": 1, "start": "2025-06-06 17:58:34.082961", "stderr": "Traceback (most recent call last):\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 145, in __init__\n    self._dbapi_connection = engine.raw_connection()\n                             ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 3297, in raw_connection\n    return self.pool.connect()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n    return _ConnectionFairy._checkout(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 1264, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 713, in checkout\n    rec = pool._do_get()\n          ^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get\n    with util.safe_reraise():\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n    return self._create_connection()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n    return _ConnectionRecord(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 675, in __init__\n    self.__connect()\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 901, in __connect\n    with util.safe_reraise():\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 897, in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py\", line 646, in connect\n    return dialect.connect(*cargs, **cparams)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py\", line 625, in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/psycopg2/__init__.py\", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\npsycopg2.OperationalError: connection to server at \"db-app-flask.c87iueymmzz1.us-east-1.rds.amazonaws.com\" (172.31.80.197), port 5432 failed: timeout expired\n\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/var/www/article_pool/venv/bin/flask\", line 8, in <module>\n    sys.exit(main())\n             ^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/flask/cli.py\", line 1131, in main\n    cli.main()\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/click/core.py\", line 1363, in main\n    rv = self.invoke(ctx)\n         ^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/click/core.py\", line 1830, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/click/core.py\", line 1830, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/click/core.py\", line 1226, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/click/core.py\", line 794, in invoke\n    return callback(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/click/decorators.py\", line 34, in new_func\n    return f(get_current_context(), *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/flask/cli.py\", line 400, in decorator\n    return ctx.invoke(f, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/click/core.py\", line 794, in invoke\n    return callback(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/flask_migrate/cli.py\", line 157, in upgrade\n    _upgrade(directory or g.directory, revision, sql, tag, x_arg or g.x_arg)\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/flask_migrate/__init__.py\", line 111, in wrapped\n    f(*args, **kwargs)\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/flask_migrate/__init__.py\", line 200, in upgrade\n    command.upgrade(config, revision, sql=sql, tag=tag)\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/alembic/command.py\", line 483, in upgrade\n    script.run_env()\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/alembic/script/base.py\", line 551, in run_env\n    util.load_python_file(self.dir, \"env.py\")\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/alembic/util/pyfiles.py\", line 114, in load_python_file\n    module = load_module_py(module_id, path)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/alembic/util/pyfiles.py\", line 134, in load_module_py\n    spec.loader.exec_module(module)  # type: ignore\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n  File \"/var/www/article_pool/migrations/env.py\", line 113, in <module>\n    run_migrations_online()\n  File \"/var/www/article_pool/migrations/env.py\", line 99, in run_migrations_online\n    with connectable.connect() as connection:\n         ^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 3273, in connect\n    return self._connection_cls(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 147, in __init__\n    Connection._handle_dbapi_exception_noconnection(\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 2436, in _handle_dbapi_exception_noconnection\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 145, in __init__\n    self._dbapi_connection = engine.raw_connection()\n                             ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 3297, in raw_connection\n    return self.pool.connect()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n    return _ConnectionFairy._checkout(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 1264, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 713, in checkout\n    rec = pool._do_get()\n          ^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get\n    with util.safe_reraise():\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n    return self._create_connection()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n    return _ConnectionRecord(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 675, in __init__\n    self.__connect()\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 901, in __connect\n    with util.safe_reraise():\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 897, in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py\", line 646, in connect\n    return dialect.connect(*cargs, **cparams)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py\", line 625, in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/psycopg2/__init__.py\", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at \"db-app-flask.c87iueymmzz1.us-east-1.rds.amazonaws.com\" (172.31.80.197), port 5432 failed: timeout expired\n\n(Background on this error at: https://sqlalche.me/e/20/e3q8)\nTraceback (most recent call last):\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 145, in __init__\n    self._dbapi_connection = engine.raw_connection()\n                             ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 3297, in raw_connection\n    return self.pool.connect()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n    return _ConnectionFairy._checkout(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 1264, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 713, in checkout\n    rec = pool._do_get()\n          ^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get\n    with util.safe_reraise():\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n    return self._create_connection()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n    return _ConnectionRecord(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 675, in __init__\n    self.__connect()\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 901, in __connect\n    with util.safe_reraise():\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 897, in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py\", line 646, in connect\n    return dialect.connect(*cargs, **cparams)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py\", line 625, in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/psycopg2/__init__.py\", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\npsycopg2.OperationalError: connection to server at \"db-app-flask.c87iueymmzz1.us-east-1.rds.amazonaws.com\" (172.31.80.197), port 5432 failed: timeout expired\n\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/var/www/article_pool/app/create_db.py\", line 10, in <module>\n    category = Category.query.filter_by(name=cat_name).first()\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py\", line 2759, in first\n    return self.limit(1)._iter().first()  # type: ignore\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py\", line 2857, in _iter\n    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(\n                                                  ^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py\", line 2365, in execute\n    return self._execute_internal(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py\", line 2241, in _execute_internal\n    conn = self._connection_for_bind(bind)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py\", line 2110, in _connection_for_bind\n    return trans._connection_for_bind(engine, execution_options)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<string>\", line 2, in _connection_for_bind\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py\", line 139, in _go\n    ret_value = fn(self, *arg, **kw)\n                ^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py\", line 1189, in _connection_for_bind\n    conn = bind.connect()\n           ^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 3273, in connect\n    return self._connection_cls(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 147, in __init__\n    Connection._handle_dbapi_exception_noconnection(\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 2436, in _handle_dbapi_exception_noconnection\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 145, in __init__\n    self._dbapi_connection = engine.raw_connection()\n                             ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 3297, in raw_connection\n    return self.pool.connect()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n    return _ConnectionFairy._checkout(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 1264, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 713, in checkout\n    rec = pool._do_get()\n          ^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get\n    with util.safe_reraise():\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n    return self._create_connection()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n    return _ConnectionRecord(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 675, in __init__\n    self.__connect()\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 901, in __connect\n    with util.safe_reraise():\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 897, in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py\", line 646, in connect\n    return dialect.connect(*cargs, **cparams)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py\", line 625, in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/psycopg2/__init__.py\", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at \"db-app-flask.c87iueymmzz1.us-east-1.rds.amazonaws.com\" (172.31.80.197), port 5432 failed: timeout expired\n\n(Background on this error at: https://sqlalche.me/e/20/e3q8)", "stderr_lines": ["Traceback (most recent call last):", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 145, in __init__", "    self._dbapi_connection = engine.raw_connection()", "                             ^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 3297, in raw_connection", "    return self.pool.connect()", "           ^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 449, in connect", "    return _ConnectionFairy._checkout(self)", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 1264, in _checkout", "    fairy = _ConnectionRecord.checkout(pool)", "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 713, in checkout", "    rec = pool._do_get()", "          ^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get", "    with util.safe_reraise():", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__", "    raise exc_value.with_traceback(exc_tb)", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get", "    return self._create_connection()", "           ^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection", "    return _ConnectionRecord(self)", "           ^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 675, in __init__", "    self.__connect()", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 901, in __connect", "    with util.safe_reraise():", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__", "    raise exc_value.with_traceback(exc_tb)", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 897, in __connect", "    self.dbapi_connection = connection = pool._invoke_creator(self)", "                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py\", line 646, in connect", "    return dialect.connect(*cargs, **cparams)", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py\", line 625, in connect", "    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/psycopg2/__init__.py\", line 122, in connect", "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "psycopg2.OperationalError: connection to server at \"db-app-flask.c87iueymmzz1.us-east-1.rds.amazonaws.com\" (172.31.80.197), port 5432 failed: timeout expired", "", "", "The above exception was the direct cause of the following exception:", "", "Traceback (most recent call last):", "  File \"/var/www/article_pool/venv/bin/flask\", line 8, in <module>", "    sys.exit(main())", "             ^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/flask/cli.py\", line 1131, in main", "    cli.main()", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/click/core.py\", line 1363, in main", "    rv = self.invoke(ctx)", "         ^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/click/core.py\", line 1830, in invoke", "    return _process_result(sub_ctx.command.invoke(sub_ctx))", "                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/click/core.py\", line 1830, in invoke", "    return _process_result(sub_ctx.command.invoke(sub_ctx))", "                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/click/core.py\", line 1226, in invoke", "    return ctx.invoke(self.callback, **ctx.params)", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/click/core.py\", line 794, in invoke", "    return callback(*args, **kwargs)", "           ^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/click/decorators.py\", line 34, in new_func", "    return f(get_current_context(), *args, **kwargs)", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/flask/cli.py\", line 400, in decorator", "    return ctx.invoke(f, *args, **kwargs)", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/click/core.py\", line 794, in invoke", "    return callback(*args, **kwargs)", "           ^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/flask_migrate/cli.py\", line 157, in upgrade", "    _upgrade(directory or g.directory, revision, sql, tag, x_arg or g.x_arg)", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/flask_migrate/__init__.py\", line 111, in wrapped", "    f(*args, **kwargs)", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/flask_migrate/__init__.py\", line 200, in upgrade", "    command.upgrade(config, revision, sql=sql, tag=tag)", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/alembic/command.py\", line 483, in upgrade", "    script.run_env()", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/alembic/script/base.py\", line 551, in run_env", "    util.load_python_file(self.dir, \"env.py\")", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/alembic/util/pyfiles.py\", line 114, in load_python_file", "    module = load_module_py(module_id, path)", "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/alembic/util/pyfiles.py\", line 134, in load_module_py", "    spec.loader.exec_module(module)  # type: ignore", "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module", "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed", "  File \"/var/www/article_pool/migrations/env.py\", line 113, in <module>", "    run_migrations_online()", "  File \"/var/www/article_pool/migrations/env.py\", line 99, in run_migrations_online", "    with connectable.connect() as connection:", "         ^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 3273, in connect", "    return self._connection_cls(self)", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 147, in __init__", "    Connection._handle_dbapi_exception_noconnection(", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 2436, in _handle_dbapi_exception_noconnection", "    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 145, in __init__", "    self._dbapi_connection = engine.raw_connection()", "                             ^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 3297, in raw_connection", "    return self.pool.connect()", "           ^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 449, in connect", "    return _ConnectionFairy._checkout(self)", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 1264, in _checkout", "    fairy = _ConnectionRecord.checkout(pool)", "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 713, in checkout", "    rec = pool._do_get()", "          ^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get", "    with util.safe_reraise():", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__", "    raise exc_value.with_traceback(exc_tb)", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get", "    return self._create_connection()", "           ^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection", "    return _ConnectionRecord(self)", "           ^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 675, in __init__", "    self.__connect()", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 901, in __connect", "    with util.safe_reraise():", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__", "    raise exc_value.with_traceback(exc_tb)", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 897, in __connect", "    self.dbapi_connection = connection = pool._invoke_creator(self)", "                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py\", line 646, in connect", "    return dialect.connect(*cargs, **cparams)", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py\", line 625, in connect", "    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/psycopg2/__init__.py\", line 122, in connect", "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at \"db-app-flask.c87iueymmzz1.us-east-1.rds.amazonaws.com\" (172.31.80.197), port 5432 failed: timeout expired", "", "(Background on this error at: https://sqlalche.me/e/20/e3q8)", "Traceback (most recent call last):", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 145, in __init__", "    self._dbapi_connection = engine.raw_connection()", "                             ^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 3297, in raw_connection", "    return self.pool.connect()", "           ^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 449, in connect", "    return _ConnectionFairy._checkout(self)", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 1264, in _checkout", "    fairy = _ConnectionRecord.checkout(pool)", "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 713, in checkout", "    rec = pool._do_get()", "          ^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get", "    with util.safe_reraise():", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__", "    raise exc_value.with_traceback(exc_tb)", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get", "    return self._create_connection()", "           ^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection", "    return _ConnectionRecord(self)", "           ^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 675, in __init__", "    self.__connect()", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 901, in __connect", "    with util.safe_reraise():", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__", "    raise exc_value.with_traceback(exc_tb)", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 897, in __connect", "    self.dbapi_connection = connection = pool._invoke_creator(self)", "                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py\", line 646, in connect", "    return dialect.connect(*cargs, **cparams)", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py\", line 625, in connect", "    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/psycopg2/__init__.py\", line 122, in connect", "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "psycopg2.OperationalError: connection to server at \"db-app-flask.c87iueymmzz1.us-east-1.rds.amazonaws.com\" (172.31.80.197), port 5432 failed: timeout expired", "", "", "The above exception was the direct cause of the following exception:", "", "Traceback (most recent call last):", "  File \"<frozen runpy>\", line 198, in _run_module_as_main", "  File \"<frozen runpy>\", line 88, in _run_code", "  File \"/var/www/article_pool/app/create_db.py\", line 10, in <module>", "    category = Category.query.filter_by(name=cat_name).first()", "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py\", line 2759, in first", "    return self.limit(1)._iter().first()  # type: ignore", "           ^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py\", line 2857, in _iter", "    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(", "                                                  ^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py\", line 2365, in execute", "    return self._execute_internal(", "           ^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py\", line 2241, in _execute_internal", "    conn = self._connection_for_bind(bind)", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py\", line 2110, in _connection_for_bind", "    return trans._connection_for_bind(engine, execution_options)", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"<string>\", line 2, in _connection_for_bind", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py\", line 139, in _go", "    ret_value = fn(self, *arg, **kw)", "                ^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py\", line 1189, in _connection_for_bind", "    conn = bind.connect()", "           ^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 3273, in connect", "    return self._connection_cls(self)", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 147, in __init__", "    Connection._handle_dbapi_exception_noconnection(", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 2436, in _handle_dbapi_exception_noconnection", "    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 145, in __init__", "    self._dbapi_connection = engine.raw_connection()", "                             ^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 3297, in raw_connection", "    return self.pool.connect()", "           ^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 449, in connect", "    return _ConnectionFairy._checkout(self)", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 1264, in _checkout", "    fairy = _ConnectionRecord.checkout(pool)", "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 713, in checkout", "    rec = pool._do_get()", "          ^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get", "    with util.safe_reraise():", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__", "    raise exc_value.with_traceback(exc_tb)", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get", "    return self._create_connection()", "           ^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection", "    return _ConnectionRecord(self)", "           ^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 675, in __init__", "    self.__connect()", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 901, in __connect", "    with util.safe_reraise():", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__", "    raise exc_value.with_traceback(exc_tb)", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 897, in __connect", "    self.dbapi_connection = connection = pool._invoke_creator(self)", "                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py\", line 646, in connect", "    return dialect.connect(*cargs, **cparams)", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py\", line 625, in connect", "    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "  File \"/var/www/article_pool/venv/lib/python3.12/site-packages/psycopg2/__init__.py\", line 122, in connect", "    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at \"db-app-flask.c87iueymmzz1.us-east-1.rds.amazonaws.com\" (172.31.80.197), port 5432 failed: timeout expired", "", "(Background on this error at: https://sqlalche.me/e/20/e3q8)"], "stdout": "Populating default categories (assuming tables are created by migrations)...", "stdout_lines": ["Populating default categories (assuming tables are created by migrations)..."]}




Tarea ansible:

    - name: Run Flask DB migrations and create DB
      shell: |
        . "{{ venv_dir }}/bin/activate"
        export FLASK_APP=app.py
        flask db upgrade
        python3 -m app.create_db
      args:
        chdir: "{{ app_dir }}"
        executable: /bin/bash